// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: transactions.proto
// Protobuf Java Version: 4.28.2

package com.example.transactions_service.grpc;

public interface ChargePurchaseRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:profkom.transactions.ChargePurchaseRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 buyer_user_id = 1;</code>
   * @return The buyerUserId.
   */
  long getBuyerUserId();

  /**
   * <code>int64 amount = 2;</code>
   * @return The amount.
   */
  long getAmount();

  /**
   * <code>string purchase_id = 3;</code>
   * @return The purchaseId.
   */
  java.lang.String getPurchaseId();
  /**
   * <code>string purchase_id = 3;</code>
   * @return The bytes for purchaseId.
   */
  com.google.protobuf.ByteString
      getPurchaseIdBytes();

  /**
   * <code>string description = 4;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 4;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();
}
