// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: transactions.proto
// Protobuf Java Version: 4.28.2

package com.example.transactions_service.grpc;

public interface TransactionInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:profkom.transactions.TransactionInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string transaction_id = 1;</code>
   * @return The transactionId.
   */
  java.lang.String getTransactionId();
  /**
   * <code>string transaction_id = 1;</code>
   * @return The bytes for transactionId.
   */
  com.google.protobuf.ByteString
      getTransactionIdBytes();

  /**
   * <code>string sender_wallet_id = 2;</code>
   * @return The senderWalletId.
   */
  java.lang.String getSenderWalletId();
  /**
   * <code>string sender_wallet_id = 2;</code>
   * @return The bytes for senderWalletId.
   */
  com.google.protobuf.ByteString
      getSenderWalletIdBytes();

  /**
   * <code>string receiver_wallet_id = 3;</code>
   * @return The receiverWalletId.
   */
  java.lang.String getReceiverWalletId();
  /**
   * <code>string receiver_wallet_id = 3;</code>
   * @return The bytes for receiverWalletId.
   */
  com.google.protobuf.ByteString
      getReceiverWalletIdBytes();

  /**
   * <code>string type = 4;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string type = 4;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>int64 amount = 5;</code>
   * @return The amount.
   */
  long getAmount();

  /**
   * <code>string status = 6;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 6;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>string related_event_id = 7;</code>
   * @return The relatedEventId.
   */
  java.lang.String getRelatedEventId();
  /**
   * <code>string related_event_id = 7;</code>
   * @return The bytes for relatedEventId.
   */
  com.google.protobuf.ByteString
      getRelatedEventIdBytes();

  /**
   * <code>string related_purchase_id = 8;</code>
   * @return The relatedPurchaseId.
   */
  java.lang.String getRelatedPurchaseId();
  /**
   * <code>string related_purchase_id = 8;</code>
   * @return The bytes for relatedPurchaseId.
   */
  com.google.protobuf.ByteString
      getRelatedPurchaseIdBytes();

  /**
   * <code>string description = 9;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 9;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>string created_at = 10;</code>
   * @return The createdAt.
   */
  java.lang.String getCreatedAt();
  /**
   * <code>string created_at = 10;</code>
   * @return The bytes for createdAt.
   */
  com.google.protobuf.ByteString
      getCreatedAtBytes();
}
