// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: transactions.proto
// Protobuf Java Version: 4.28.2

package com.example.transactions_service.grpc;

public final class Transactions {
  private Transactions() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      Transactions.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_profkom_transactions_AwardEventRewardRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_profkom_transactions_AwardEventRewardRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_profkom_transactions_ChargePurchaseRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_profkom_transactions_ChargePurchaseRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_profkom_transactions_RefundPurchaseRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_profkom_transactions_RefundPurchaseRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_profkom_transactions_TransactionInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_profkom_transactions_TransactionInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022transactions.proto\022\024profkom.transactio" +
      "ns\"\204\001\n\027AwardEventRewardRequest\022\030\n\020review" +
      "er_user_id\030\001 \001(\003\022\030\n\020receiver_user_id\030\002 \001" +
      "(\003\022\016\n\006amount\030\003 \001(\003\022\020\n\010event_id\030\004 \001(\t\022\023\n\013" +
      "description\030\005 \001(\t\"h\n\025ChargePurchaseReque" +
      "st\022\025\n\rbuyer_user_id\030\001 \001(\003\022\016\n\006amount\030\002 \001(" +
      "\003\022\023\n\013purchase_id\030\003 \001(\t\022\023\n\013description\030\004 " +
      "\001(\t\"h\n\025RefundPurchaseRequest\022\025\n\rbuyer_us" +
      "er_id\030\001 \001(\003\022\016\n\006amount\030\002 \001(\003\022\023\n\013purchase_" +
      "id\030\003 \001(\t\022\023\n\013description\030\004 \001(\t\"\355\001\n\017Transa" +
      "ctionInfo\022\026\n\016transaction_id\030\001 \001(\t\022\030\n\020sen" +
      "der_wallet_id\030\002 \001(\t\022\032\n\022receiver_wallet_i" +
      "d\030\003 \001(\t\022\014\n\004type\030\004 \001(\t\022\016\n\006amount\030\005 \001(\003\022\016\n" +
      "\006status\030\006 \001(\t\022\030\n\020related_event_id\030\007 \001(\t\022" +
      "\033\n\023related_purchase_id\030\010 \001(\t\022\023\n\013descript" +
      "ion\030\t \001(\t\022\022\n\ncreated_at\030\n \001(\t2\316\002\n\026Transa" +
      "ctionGrpcService\022h\n\020AwardEventReward\022-.p" +
      "rofkom.transactions.AwardEventRewardRequ" +
      "est\032%.profkom.transactions.TransactionIn" +
      "fo\022d\n\016ChargePurchase\022+.profkom.transacti" +
      "ons.ChargePurchaseRequest\032%.profkom.tran" +
      "sactions.TransactionInfo\022d\n\016RefundPurcha" +
      "se\022+.profkom.transactions.RefundPurchase" +
      "Request\032%.profkom.transactions.Transacti" +
      "onInfoB)\n%com.example.transactions_servi" +
      "ce.grpcP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_profkom_transactions_AwardEventRewardRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_profkom_transactions_AwardEventRewardRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_profkom_transactions_AwardEventRewardRequest_descriptor,
        new java.lang.String[] { "ReviewerUserId", "ReceiverUserId", "Amount", "EventId", "Description", });
    internal_static_profkom_transactions_ChargePurchaseRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_profkom_transactions_ChargePurchaseRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_profkom_transactions_ChargePurchaseRequest_descriptor,
        new java.lang.String[] { "BuyerUserId", "Amount", "PurchaseId", "Description", });
    internal_static_profkom_transactions_RefundPurchaseRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_profkom_transactions_RefundPurchaseRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_profkom_transactions_RefundPurchaseRequest_descriptor,
        new java.lang.String[] { "BuyerUserId", "Amount", "PurchaseId", "Description", });
    internal_static_profkom_transactions_TransactionInfo_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_profkom_transactions_TransactionInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_profkom_transactions_TransactionInfo_descriptor,
        new java.lang.String[] { "TransactionId", "SenderWalletId", "ReceiverWalletId", "Type", "Amount", "Status", "RelatedEventId", "RelatedPurchaseId", "Description", "CreatedAt", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
