// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: transactions.proto
// Protobuf Java Version: 4.28.2

package com.example.transactions_service.grpc;

/**
 * Protobuf type {@code profkom.transactions.TransactionInfo}
 */
public final class TransactionInfo extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:profkom.transactions.TransactionInfo)
    TransactionInfoOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      TransactionInfo.class.getName());
  }
  // Use TransactionInfo.newBuilder() to construct.
  private TransactionInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private TransactionInfo() {
    transactionId_ = "";
    senderWalletId_ = "";
    receiverWalletId_ = "";
    type_ = "";
    status_ = "";
    relatedEventId_ = "";
    relatedPurchaseId_ = "";
    description_ = "";
    createdAt_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.transactions_service.grpc.Transactions.internal_static_profkom_transactions_TransactionInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.transactions_service.grpc.Transactions.internal_static_profkom_transactions_TransactionInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.transactions_service.grpc.TransactionInfo.class, com.example.transactions_service.grpc.TransactionInfo.Builder.class);
  }

  public static final int TRANSACTION_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object transactionId_ = "";
  /**
   * <code>string transaction_id = 1;</code>
   * @return The transactionId.
   */
  @java.lang.Override
  public java.lang.String getTransactionId() {
    java.lang.Object ref = transactionId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      transactionId_ = s;
      return s;
    }
  }
  /**
   * <code>string transaction_id = 1;</code>
   * @return The bytes for transactionId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTransactionIdBytes() {
    java.lang.Object ref = transactionId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      transactionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SENDER_WALLET_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object senderWalletId_ = "";
  /**
   * <code>string sender_wallet_id = 2;</code>
   * @return The senderWalletId.
   */
  @java.lang.Override
  public java.lang.String getSenderWalletId() {
    java.lang.Object ref = senderWalletId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      senderWalletId_ = s;
      return s;
    }
  }
  /**
   * <code>string sender_wallet_id = 2;</code>
   * @return The bytes for senderWalletId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSenderWalletIdBytes() {
    java.lang.Object ref = senderWalletId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      senderWalletId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RECEIVER_WALLET_ID_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object receiverWalletId_ = "";
  /**
   * <code>string receiver_wallet_id = 3;</code>
   * @return The receiverWalletId.
   */
  @java.lang.Override
  public java.lang.String getReceiverWalletId() {
    java.lang.Object ref = receiverWalletId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      receiverWalletId_ = s;
      return s;
    }
  }
  /**
   * <code>string receiver_wallet_id = 3;</code>
   * @return The bytes for receiverWalletId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReceiverWalletIdBytes() {
    java.lang.Object ref = receiverWalletId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      receiverWalletId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPE_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object type_ = "";
  /**
   * <code>string type = 4;</code>
   * @return The type.
   */
  @java.lang.Override
  public java.lang.String getType() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      type_ = s;
      return s;
    }
  }
  /**
   * <code>string type = 4;</code>
   * @return The bytes for type.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTypeBytes() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      type_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AMOUNT_FIELD_NUMBER = 5;
  private long amount_ = 0L;
  /**
   * <code>int64 amount = 5;</code>
   * @return The amount.
   */
  @java.lang.Override
  public long getAmount() {
    return amount_;
  }

  public static final int STATUS_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object status_ = "";
  /**
   * <code>string status = 6;</code>
   * @return The status.
   */
  @java.lang.Override
  public java.lang.String getStatus() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      status_ = s;
      return s;
    }
  }
  /**
   * <code>string status = 6;</code>
   * @return The bytes for status.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStatusBytes() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      status_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RELATED_EVENT_ID_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object relatedEventId_ = "";
  /**
   * <code>string related_event_id = 7;</code>
   * @return The relatedEventId.
   */
  @java.lang.Override
  public java.lang.String getRelatedEventId() {
    java.lang.Object ref = relatedEventId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      relatedEventId_ = s;
      return s;
    }
  }
  /**
   * <code>string related_event_id = 7;</code>
   * @return The bytes for relatedEventId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRelatedEventIdBytes() {
    java.lang.Object ref = relatedEventId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      relatedEventId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RELATED_PURCHASE_ID_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object relatedPurchaseId_ = "";
  /**
   * <code>string related_purchase_id = 8;</code>
   * @return The relatedPurchaseId.
   */
  @java.lang.Override
  public java.lang.String getRelatedPurchaseId() {
    java.lang.Object ref = relatedPurchaseId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      relatedPurchaseId_ = s;
      return s;
    }
  }
  /**
   * <code>string related_purchase_id = 8;</code>
   * @return The bytes for relatedPurchaseId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRelatedPurchaseIdBytes() {
    java.lang.Object ref = relatedPurchaseId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      relatedPurchaseId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private volatile java.lang.Object description_ = "";
  /**
   * <code>string description = 9;</code>
   * @return The description.
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <code>string description = 9;</code>
   * @return The bytes for description.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CREATED_AT_FIELD_NUMBER = 10;
  @SuppressWarnings("serial")
  private volatile java.lang.Object createdAt_ = "";
  /**
   * <code>string created_at = 10;</code>
   * @return The createdAt.
   */
  @java.lang.Override
  public java.lang.String getCreatedAt() {
    java.lang.Object ref = createdAt_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      createdAt_ = s;
      return s;
    }
  }
  /**
   * <code>string created_at = 10;</code>
   * @return The bytes for createdAt.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCreatedAtBytes() {
    java.lang.Object ref = createdAt_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      createdAt_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(transactionId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, transactionId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(senderWalletId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, senderWalletId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(receiverWalletId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, receiverWalletId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(type_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, type_);
    }
    if (amount_ != 0L) {
      output.writeInt64(5, amount_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(status_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, status_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(relatedEventId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 7, relatedEventId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(relatedPurchaseId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 8, relatedPurchaseId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(description_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 9, description_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(createdAt_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 10, createdAt_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(transactionId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, transactionId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(senderWalletId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, senderWalletId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(receiverWalletId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, receiverWalletId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(type_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, type_);
    }
    if (amount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, amount_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(status_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, status_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(relatedEventId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(7, relatedEventId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(relatedPurchaseId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(8, relatedPurchaseId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(description_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(9, description_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(createdAt_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(10, createdAt_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.transactions_service.grpc.TransactionInfo)) {
      return super.equals(obj);
    }
    com.example.transactions_service.grpc.TransactionInfo other = (com.example.transactions_service.grpc.TransactionInfo) obj;

    if (!getTransactionId()
        .equals(other.getTransactionId())) return false;
    if (!getSenderWalletId()
        .equals(other.getSenderWalletId())) return false;
    if (!getReceiverWalletId()
        .equals(other.getReceiverWalletId())) return false;
    if (!getType()
        .equals(other.getType())) return false;
    if (getAmount()
        != other.getAmount()) return false;
    if (!getStatus()
        .equals(other.getStatus())) return false;
    if (!getRelatedEventId()
        .equals(other.getRelatedEventId())) return false;
    if (!getRelatedPurchaseId()
        .equals(other.getRelatedPurchaseId())) return false;
    if (!getDescription()
        .equals(other.getDescription())) return false;
    if (!getCreatedAt()
        .equals(other.getCreatedAt())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TRANSACTION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTransactionId().hashCode();
    hash = (37 * hash) + SENDER_WALLET_ID_FIELD_NUMBER;
    hash = (53 * hash) + getSenderWalletId().hashCode();
    hash = (37 * hash) + RECEIVER_WALLET_ID_FIELD_NUMBER;
    hash = (53 * hash) + getReceiverWalletId().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType().hashCode();
    hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getAmount());
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus().hashCode();
    hash = (37 * hash) + RELATED_EVENT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getRelatedEventId().hashCode();
    hash = (37 * hash) + RELATED_PURCHASE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getRelatedPurchaseId().hashCode();
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    hash = (37 * hash) + CREATED_AT_FIELD_NUMBER;
    hash = (53 * hash) + getCreatedAt().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.transactions_service.grpc.TransactionInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.transactions_service.grpc.TransactionInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.transactions_service.grpc.TransactionInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.transactions_service.grpc.TransactionInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.transactions_service.grpc.TransactionInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.transactions_service.grpc.TransactionInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.transactions_service.grpc.TransactionInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.example.transactions_service.grpc.TransactionInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.example.transactions_service.grpc.TransactionInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.example.transactions_service.grpc.TransactionInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.transactions_service.grpc.TransactionInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.example.transactions_service.grpc.TransactionInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.transactions_service.grpc.TransactionInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code profkom.transactions.TransactionInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:profkom.transactions.TransactionInfo)
      com.example.transactions_service.grpc.TransactionInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.transactions_service.grpc.Transactions.internal_static_profkom_transactions_TransactionInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.transactions_service.grpc.Transactions.internal_static_profkom_transactions_TransactionInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.transactions_service.grpc.TransactionInfo.class, com.example.transactions_service.grpc.TransactionInfo.Builder.class);
    }

    // Construct using com.example.transactions_service.grpc.TransactionInfo.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      transactionId_ = "";
      senderWalletId_ = "";
      receiverWalletId_ = "";
      type_ = "";
      amount_ = 0L;
      status_ = "";
      relatedEventId_ = "";
      relatedPurchaseId_ = "";
      description_ = "";
      createdAt_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.transactions_service.grpc.Transactions.internal_static_profkom_transactions_TransactionInfo_descriptor;
    }

    @java.lang.Override
    public com.example.transactions_service.grpc.TransactionInfo getDefaultInstanceForType() {
      return com.example.transactions_service.grpc.TransactionInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.transactions_service.grpc.TransactionInfo build() {
      com.example.transactions_service.grpc.TransactionInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.transactions_service.grpc.TransactionInfo buildPartial() {
      com.example.transactions_service.grpc.TransactionInfo result = new com.example.transactions_service.grpc.TransactionInfo(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.example.transactions_service.grpc.TransactionInfo result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.transactionId_ = transactionId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.senderWalletId_ = senderWalletId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.receiverWalletId_ = receiverWalletId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.type_ = type_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.amount_ = amount_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.status_ = status_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.relatedEventId_ = relatedEventId_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.relatedPurchaseId_ = relatedPurchaseId_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.description_ = description_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.createdAt_ = createdAt_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.transactions_service.grpc.TransactionInfo) {
        return mergeFrom((com.example.transactions_service.grpc.TransactionInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.transactions_service.grpc.TransactionInfo other) {
      if (other == com.example.transactions_service.grpc.TransactionInfo.getDefaultInstance()) return this;
      if (!other.getTransactionId().isEmpty()) {
        transactionId_ = other.transactionId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getSenderWalletId().isEmpty()) {
        senderWalletId_ = other.senderWalletId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getReceiverWalletId().isEmpty()) {
        receiverWalletId_ = other.receiverWalletId_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getType().isEmpty()) {
        type_ = other.type_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.getAmount() != 0L) {
        setAmount(other.getAmount());
      }
      if (!other.getStatus().isEmpty()) {
        status_ = other.status_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (!other.getRelatedEventId().isEmpty()) {
        relatedEventId_ = other.relatedEventId_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (!other.getRelatedPurchaseId().isEmpty()) {
        relatedPurchaseId_ = other.relatedPurchaseId_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        bitField0_ |= 0x00000100;
        onChanged();
      }
      if (!other.getCreatedAt().isEmpty()) {
        createdAt_ = other.createdAt_;
        bitField0_ |= 0x00000200;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              transactionId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              senderWalletId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              receiverWalletId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              type_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 40: {
              amount_ = input.readInt64();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 50: {
              status_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              relatedEventId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              relatedPurchaseId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 74: {
              description_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            case 82: {
              createdAt_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000200;
              break;
            } // case 82
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object transactionId_ = "";
    /**
     * <code>string transaction_id = 1;</code>
     * @return The transactionId.
     */
    public java.lang.String getTransactionId() {
      java.lang.Object ref = transactionId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        transactionId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string transaction_id = 1;</code>
     * @return The bytes for transactionId.
     */
    public com.google.protobuf.ByteString
        getTransactionIdBytes() {
      java.lang.Object ref = transactionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        transactionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string transaction_id = 1;</code>
     * @param value The transactionId to set.
     * @return This builder for chaining.
     */
    public Builder setTransactionId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      transactionId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string transaction_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTransactionId() {
      transactionId_ = getDefaultInstance().getTransactionId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string transaction_id = 1;</code>
     * @param value The bytes for transactionId to set.
     * @return This builder for chaining.
     */
    public Builder setTransactionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      transactionId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object senderWalletId_ = "";
    /**
     * <code>string sender_wallet_id = 2;</code>
     * @return The senderWalletId.
     */
    public java.lang.String getSenderWalletId() {
      java.lang.Object ref = senderWalletId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        senderWalletId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sender_wallet_id = 2;</code>
     * @return The bytes for senderWalletId.
     */
    public com.google.protobuf.ByteString
        getSenderWalletIdBytes() {
      java.lang.Object ref = senderWalletId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        senderWalletId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sender_wallet_id = 2;</code>
     * @param value The senderWalletId to set.
     * @return This builder for chaining.
     */
    public Builder setSenderWalletId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      senderWalletId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string sender_wallet_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSenderWalletId() {
      senderWalletId_ = getDefaultInstance().getSenderWalletId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string sender_wallet_id = 2;</code>
     * @param value The bytes for senderWalletId to set.
     * @return This builder for chaining.
     */
    public Builder setSenderWalletIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      senderWalletId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object receiverWalletId_ = "";
    /**
     * <code>string receiver_wallet_id = 3;</code>
     * @return The receiverWalletId.
     */
    public java.lang.String getReceiverWalletId() {
      java.lang.Object ref = receiverWalletId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        receiverWalletId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string receiver_wallet_id = 3;</code>
     * @return The bytes for receiverWalletId.
     */
    public com.google.protobuf.ByteString
        getReceiverWalletIdBytes() {
      java.lang.Object ref = receiverWalletId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        receiverWalletId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string receiver_wallet_id = 3;</code>
     * @param value The receiverWalletId to set.
     * @return This builder for chaining.
     */
    public Builder setReceiverWalletId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      receiverWalletId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string receiver_wallet_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearReceiverWalletId() {
      receiverWalletId_ = getDefaultInstance().getReceiverWalletId();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string receiver_wallet_id = 3;</code>
     * @param value The bytes for receiverWalletId to set.
     * @return This builder for chaining.
     */
    public Builder setReceiverWalletIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      receiverWalletId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object type_ = "";
    /**
     * <code>string type = 4;</code>
     * @return The type.
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string type = 4;</code>
     * @return The bytes for type.
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string type = 4;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      type_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string type = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      type_ = getDefaultInstance().getType();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string type = 4;</code>
     * @param value The bytes for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      type_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private long amount_ ;
    /**
     * <code>int64 amount = 5;</code>
     * @return The amount.
     */
    @java.lang.Override
    public long getAmount() {
      return amount_;
    }
    /**
     * <code>int64 amount = 5;</code>
     * @param value The amount to set.
     * @return This builder for chaining.
     */
    public Builder setAmount(long value) {

      amount_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int64 amount = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearAmount() {
      bitField0_ = (bitField0_ & ~0x00000010);
      amount_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object status_ = "";
    /**
     * <code>string status = 6;</code>
     * @return The status.
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string status = 6;</code>
     * @return The bytes for status.
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string status = 6;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      status_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string status = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      status_ = getDefaultInstance().getStatus();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string status = 6;</code>
     * @param value The bytes for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      status_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private java.lang.Object relatedEventId_ = "";
    /**
     * <code>string related_event_id = 7;</code>
     * @return The relatedEventId.
     */
    public java.lang.String getRelatedEventId() {
      java.lang.Object ref = relatedEventId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        relatedEventId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string related_event_id = 7;</code>
     * @return The bytes for relatedEventId.
     */
    public com.google.protobuf.ByteString
        getRelatedEventIdBytes() {
      java.lang.Object ref = relatedEventId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        relatedEventId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string related_event_id = 7;</code>
     * @param value The relatedEventId to set.
     * @return This builder for chaining.
     */
    public Builder setRelatedEventId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      relatedEventId_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>string related_event_id = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearRelatedEventId() {
      relatedEventId_ = getDefaultInstance().getRelatedEventId();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>string related_event_id = 7;</code>
     * @param value The bytes for relatedEventId to set.
     * @return This builder for chaining.
     */
    public Builder setRelatedEventIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      relatedEventId_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private java.lang.Object relatedPurchaseId_ = "";
    /**
     * <code>string related_purchase_id = 8;</code>
     * @return The relatedPurchaseId.
     */
    public java.lang.String getRelatedPurchaseId() {
      java.lang.Object ref = relatedPurchaseId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        relatedPurchaseId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string related_purchase_id = 8;</code>
     * @return The bytes for relatedPurchaseId.
     */
    public com.google.protobuf.ByteString
        getRelatedPurchaseIdBytes() {
      java.lang.Object ref = relatedPurchaseId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        relatedPurchaseId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string related_purchase_id = 8;</code>
     * @param value The relatedPurchaseId to set.
     * @return This builder for chaining.
     */
    public Builder setRelatedPurchaseId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      relatedPurchaseId_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>string related_purchase_id = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearRelatedPurchaseId() {
      relatedPurchaseId_ = getDefaultInstance().getRelatedPurchaseId();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <code>string related_purchase_id = 8;</code>
     * @param value The bytes for relatedPurchaseId to set.
     * @return This builder for chaining.
     */
    public Builder setRelatedPurchaseIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      relatedPurchaseId_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     * <code>string description = 9;</code>
     * @return The description.
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string description = 9;</code>
     * @return The bytes for description.
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string description = 9;</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      description_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>string description = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      description_ = getDefaultInstance().getDescription();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <code>string description = 9;</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      description_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    private java.lang.Object createdAt_ = "";
    /**
     * <code>string created_at = 10;</code>
     * @return The createdAt.
     */
    public java.lang.String getCreatedAt() {
      java.lang.Object ref = createdAt_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        createdAt_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string created_at = 10;</code>
     * @return The bytes for createdAt.
     */
    public com.google.protobuf.ByteString
        getCreatedAtBytes() {
      java.lang.Object ref = createdAt_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        createdAt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string created_at = 10;</code>
     * @param value The createdAt to set.
     * @return This builder for chaining.
     */
    public Builder setCreatedAt(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      createdAt_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>string created_at = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearCreatedAt() {
      createdAt_ = getDefaultInstance().getCreatedAt();
      bitField0_ = (bitField0_ & ~0x00000200);
      onChanged();
      return this;
    }
    /**
     * <code>string created_at = 10;</code>
     * @param value The bytes for createdAt to set.
     * @return This builder for chaining.
     */
    public Builder setCreatedAtBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      createdAt_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:profkom.transactions.TransactionInfo)
  }

  // @@protoc_insertion_point(class_scope:profkom.transactions.TransactionInfo)
  private static final com.example.transactions_service.grpc.TransactionInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.transactions_service.grpc.TransactionInfo();
  }

  public static com.example.transactions_service.grpc.TransactionInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TransactionInfo>
      PARSER = new com.google.protobuf.AbstractParser<TransactionInfo>() {
    @java.lang.Override
    public TransactionInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TransactionInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TransactionInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.transactions_service.grpc.TransactionInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

