// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: transactions.proto
// Protobuf Java Version: 4.28.2

package com.example.transactions_service.grpc;

public interface AwardEventRewardRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:profkom.transactions.AwardEventRewardRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 reviewer_user_id = 1;</code>
   * @return The reviewerUserId.
   */
  long getReviewerUserId();

  /**
   * <code>int64 receiver_user_id = 2;</code>
   * @return The receiverUserId.
   */
  long getReceiverUserId();

  /**
   * <code>int64 amount = 3;</code>
   * @return The amount.
   */
  long getAmount();

  /**
   * <code>string event_id = 4;</code>
   * @return The eventId.
   */
  java.lang.String getEventId();
  /**
   * <code>string event_id = 4;</code>
   * @return The bytes for eventId.
   */
  com.google.protobuf.ByteString
      getEventIdBytes();

  /**
   * <code>string description = 5;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 5;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();
}
