// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: event.proto
// Protobuf Java Version: 4.28.2

package com.example.events_service.grpc;

/**
 * Protobuf type {@code profkom.events.EventInfo}
 */
public final class EventInfo extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:profkom.events.EventInfo)
    EventInfoOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      EventInfo.class.getName());
  }
  // Use EventInfo.newBuilder() to construct.
  private EventInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private EventInfo() {
    eventId_ = "";
    status_ = "";
    moderationStatus_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.events_service.grpc.Event.internal_static_profkom_events_EventInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.events_service.grpc.Event.internal_static_profkom_events_EventInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.events_service.grpc.EventInfo.class, com.example.events_service.grpc.EventInfo.Builder.class);
  }

  private int bitField0_;
  public static final int EVENT_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object eventId_ = "";
  /**
   * <code>string event_id = 1;</code>
   * @return The eventId.
   */
  @java.lang.Override
  public java.lang.String getEventId() {
    java.lang.Object ref = eventId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      eventId_ = s;
      return s;
    }
  }
  /**
   * <code>string event_id = 1;</code>
   * @return The bytes for eventId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEventIdBytes() {
    java.lang.Object ref = eventId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      eventId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REGISTRATION_REQUIRED_FIELD_NUMBER = 2;
  private boolean registrationRequired_ = false;
  /**
   * <code>bool registration_required = 2;</code>
   * @return The registrationRequired.
   */
  @java.lang.Override
  public boolean getRegistrationRequired() {
    return registrationRequired_;
  }

  public static final int POINTS_PER_ATTENDEE_FIELD_NUMBER = 3;
  private long pointsPerAttendee_ = 0L;
  /**
   * <code>optional int64 points_per_attendee = 3;</code>
   * @return Whether the pointsPerAttendee field is set.
   */
  @java.lang.Override
  public boolean hasPointsPerAttendee() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional int64 points_per_attendee = 3;</code>
   * @return The pointsPerAttendee.
   */
  @java.lang.Override
  public long getPointsPerAttendee() {
    return pointsPerAttendee_;
  }

  public static final int REVIEWED_BY_FIELD_NUMBER = 4;
  private long reviewedBy_ = 0L;
  /**
   * <code>optional int64 reviewed_by = 4;</code>
   * @return Whether the reviewedBy field is set.
   */
  @java.lang.Override
  public boolean hasReviewedBy() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional int64 reviewed_by = 4;</code>
   * @return The reviewedBy.
   */
  @java.lang.Override
  public long getReviewedBy() {
    return reviewedBy_;
  }

  public static final int SCHOOL_ID_FIELD_NUMBER = 5;
  private long schoolId_ = 0L;
  /**
   * <code>optional int64 school_id = 5;</code>
   * @return Whether the schoolId field is set.
   */
  @java.lang.Override
  public boolean hasSchoolId() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional int64 school_id = 5;</code>
   * @return The schoolId.
   */
  @java.lang.Override
  public long getSchoolId() {
    return schoolId_;
  }

  public static final int STATUS_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object status_ = "";
  /**
   * <code>string status = 6;</code>
   * @return The status.
   */
  @java.lang.Override
  public java.lang.String getStatus() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      status_ = s;
      return s;
    }
  }
  /**
   * <code>string status = 6;</code>
   * @return The bytes for status.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStatusBytes() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      status_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MODERATION_STATUS_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object moderationStatus_ = "";
  /**
   * <code>string moderation_status = 7;</code>
   * @return The moderationStatus.
   */
  @java.lang.Override
  public java.lang.String getModerationStatus() {
    java.lang.Object ref = moderationStatus_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      moderationStatus_ = s;
      return s;
    }
  }
  /**
   * <code>string moderation_status = 7;</code>
   * @return The bytes for moderationStatus.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getModerationStatusBytes() {
    java.lang.Object ref = moderationStatus_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      moderationStatus_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(eventId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, eventId_);
    }
    if (registrationRequired_ != false) {
      output.writeBool(2, registrationRequired_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt64(3, pointsPerAttendee_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeInt64(4, reviewedBy_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeInt64(5, schoolId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(status_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, status_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(moderationStatus_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 7, moderationStatus_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(eventId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, eventId_);
    }
    if (registrationRequired_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, registrationRequired_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, pointsPerAttendee_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, reviewedBy_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, schoolId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(status_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, status_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(moderationStatus_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(7, moderationStatus_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.events_service.grpc.EventInfo)) {
      return super.equals(obj);
    }
    com.example.events_service.grpc.EventInfo other = (com.example.events_service.grpc.EventInfo) obj;

    if (!getEventId()
        .equals(other.getEventId())) return false;
    if (getRegistrationRequired()
        != other.getRegistrationRequired()) return false;
    if (hasPointsPerAttendee() != other.hasPointsPerAttendee()) return false;
    if (hasPointsPerAttendee()) {
      if (getPointsPerAttendee()
          != other.getPointsPerAttendee()) return false;
    }
    if (hasReviewedBy() != other.hasReviewedBy()) return false;
    if (hasReviewedBy()) {
      if (getReviewedBy()
          != other.getReviewedBy()) return false;
    }
    if (hasSchoolId() != other.hasSchoolId()) return false;
    if (hasSchoolId()) {
      if (getSchoolId()
          != other.getSchoolId()) return false;
    }
    if (!getStatus()
        .equals(other.getStatus())) return false;
    if (!getModerationStatus()
        .equals(other.getModerationStatus())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + EVENT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getEventId().hashCode();
    hash = (37 * hash) + REGISTRATION_REQUIRED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getRegistrationRequired());
    if (hasPointsPerAttendee()) {
      hash = (37 * hash) + POINTS_PER_ATTENDEE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPointsPerAttendee());
    }
    if (hasReviewedBy()) {
      hash = (37 * hash) + REVIEWED_BY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getReviewedBy());
    }
    if (hasSchoolId()) {
      hash = (37 * hash) + SCHOOL_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSchoolId());
    }
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus().hashCode();
    hash = (37 * hash) + MODERATION_STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getModerationStatus().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.events_service.grpc.EventInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.events_service.grpc.EventInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.events_service.grpc.EventInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.events_service.grpc.EventInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.events_service.grpc.EventInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.events_service.grpc.EventInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.events_service.grpc.EventInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.example.events_service.grpc.EventInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.example.events_service.grpc.EventInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.example.events_service.grpc.EventInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.events_service.grpc.EventInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.example.events_service.grpc.EventInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.events_service.grpc.EventInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code profkom.events.EventInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:profkom.events.EventInfo)
      com.example.events_service.grpc.EventInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.events_service.grpc.Event.internal_static_profkom_events_EventInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.events_service.grpc.Event.internal_static_profkom_events_EventInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.events_service.grpc.EventInfo.class, com.example.events_service.grpc.EventInfo.Builder.class);
    }

    // Construct using com.example.events_service.grpc.EventInfo.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      eventId_ = "";
      registrationRequired_ = false;
      pointsPerAttendee_ = 0L;
      reviewedBy_ = 0L;
      schoolId_ = 0L;
      status_ = "";
      moderationStatus_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.events_service.grpc.Event.internal_static_profkom_events_EventInfo_descriptor;
    }

    @java.lang.Override
    public com.example.events_service.grpc.EventInfo getDefaultInstanceForType() {
      return com.example.events_service.grpc.EventInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.events_service.grpc.EventInfo build() {
      com.example.events_service.grpc.EventInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.events_service.grpc.EventInfo buildPartial() {
      com.example.events_service.grpc.EventInfo result = new com.example.events_service.grpc.EventInfo(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.example.events_service.grpc.EventInfo result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.eventId_ = eventId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.registrationRequired_ = registrationRequired_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.pointsPerAttendee_ = pointsPerAttendee_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.reviewedBy_ = reviewedBy_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.schoolId_ = schoolId_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.status_ = status_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.moderationStatus_ = moderationStatus_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.events_service.grpc.EventInfo) {
        return mergeFrom((com.example.events_service.grpc.EventInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.events_service.grpc.EventInfo other) {
      if (other == com.example.events_service.grpc.EventInfo.getDefaultInstance()) return this;
      if (!other.getEventId().isEmpty()) {
        eventId_ = other.eventId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getRegistrationRequired() != false) {
        setRegistrationRequired(other.getRegistrationRequired());
      }
      if (other.hasPointsPerAttendee()) {
        setPointsPerAttendee(other.getPointsPerAttendee());
      }
      if (other.hasReviewedBy()) {
        setReviewedBy(other.getReviewedBy());
      }
      if (other.hasSchoolId()) {
        setSchoolId(other.getSchoolId());
      }
      if (!other.getStatus().isEmpty()) {
        status_ = other.status_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (!other.getModerationStatus().isEmpty()) {
        moderationStatus_ = other.moderationStatus_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              eventId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              registrationRequired_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              pointsPerAttendee_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              reviewedBy_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              schoolId_ = input.readInt64();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 50: {
              status_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              moderationStatus_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object eventId_ = "";
    /**
     * <code>string event_id = 1;</code>
     * @return The eventId.
     */
    public java.lang.String getEventId() {
      java.lang.Object ref = eventId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        eventId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string event_id = 1;</code>
     * @return The bytes for eventId.
     */
    public com.google.protobuf.ByteString
        getEventIdBytes() {
      java.lang.Object ref = eventId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        eventId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string event_id = 1;</code>
     * @param value The eventId to set.
     * @return This builder for chaining.
     */
    public Builder setEventId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      eventId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string event_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearEventId() {
      eventId_ = getDefaultInstance().getEventId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string event_id = 1;</code>
     * @param value The bytes for eventId to set.
     * @return This builder for chaining.
     */
    public Builder setEventIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      eventId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private boolean registrationRequired_ ;
    /**
     * <code>bool registration_required = 2;</code>
     * @return The registrationRequired.
     */
    @java.lang.Override
    public boolean getRegistrationRequired() {
      return registrationRequired_;
    }
    /**
     * <code>bool registration_required = 2;</code>
     * @param value The registrationRequired to set.
     * @return This builder for chaining.
     */
    public Builder setRegistrationRequired(boolean value) {

      registrationRequired_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>bool registration_required = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearRegistrationRequired() {
      bitField0_ = (bitField0_ & ~0x00000002);
      registrationRequired_ = false;
      onChanged();
      return this;
    }

    private long pointsPerAttendee_ ;
    /**
     * <code>optional int64 points_per_attendee = 3;</code>
     * @return Whether the pointsPerAttendee field is set.
     */
    @java.lang.Override
    public boolean hasPointsPerAttendee() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int64 points_per_attendee = 3;</code>
     * @return The pointsPerAttendee.
     */
    @java.lang.Override
    public long getPointsPerAttendee() {
      return pointsPerAttendee_;
    }
    /**
     * <code>optional int64 points_per_attendee = 3;</code>
     * @param value The pointsPerAttendee to set.
     * @return This builder for chaining.
     */
    public Builder setPointsPerAttendee(long value) {

      pointsPerAttendee_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 points_per_attendee = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPointsPerAttendee() {
      bitField0_ = (bitField0_ & ~0x00000004);
      pointsPerAttendee_ = 0L;
      onChanged();
      return this;
    }

    private long reviewedBy_ ;
    /**
     * <code>optional int64 reviewed_by = 4;</code>
     * @return Whether the reviewedBy field is set.
     */
    @java.lang.Override
    public boolean hasReviewedBy() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional int64 reviewed_by = 4;</code>
     * @return The reviewedBy.
     */
    @java.lang.Override
    public long getReviewedBy() {
      return reviewedBy_;
    }
    /**
     * <code>optional int64 reviewed_by = 4;</code>
     * @param value The reviewedBy to set.
     * @return This builder for chaining.
     */
    public Builder setReviewedBy(long value) {

      reviewedBy_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 reviewed_by = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearReviewedBy() {
      bitField0_ = (bitField0_ & ~0x00000008);
      reviewedBy_ = 0L;
      onChanged();
      return this;
    }

    private long schoolId_ ;
    /**
     * <code>optional int64 school_id = 5;</code>
     * @return Whether the schoolId field is set.
     */
    @java.lang.Override
    public boolean hasSchoolId() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional int64 school_id = 5;</code>
     * @return The schoolId.
     */
    @java.lang.Override
    public long getSchoolId() {
      return schoolId_;
    }
    /**
     * <code>optional int64 school_id = 5;</code>
     * @param value The schoolId to set.
     * @return This builder for chaining.
     */
    public Builder setSchoolId(long value) {

      schoolId_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 school_id = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearSchoolId() {
      bitField0_ = (bitField0_ & ~0x00000010);
      schoolId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object status_ = "";
    /**
     * <code>string status = 6;</code>
     * @return The status.
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string status = 6;</code>
     * @return The bytes for status.
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string status = 6;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      status_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string status = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      status_ = getDefaultInstance().getStatus();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string status = 6;</code>
     * @param value The bytes for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      status_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private java.lang.Object moderationStatus_ = "";
    /**
     * <code>string moderation_status = 7;</code>
     * @return The moderationStatus.
     */
    public java.lang.String getModerationStatus() {
      java.lang.Object ref = moderationStatus_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        moderationStatus_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string moderation_status = 7;</code>
     * @return The bytes for moderationStatus.
     */
    public com.google.protobuf.ByteString
        getModerationStatusBytes() {
      java.lang.Object ref = moderationStatus_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        moderationStatus_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string moderation_status = 7;</code>
     * @param value The moderationStatus to set.
     * @return This builder for chaining.
     */
    public Builder setModerationStatus(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      moderationStatus_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>string moderation_status = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearModerationStatus() {
      moderationStatus_ = getDefaultInstance().getModerationStatus();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>string moderation_status = 7;</code>
     * @param value The bytes for moderationStatus to set.
     * @return This builder for chaining.
     */
    public Builder setModerationStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      moderationStatus_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:profkom.events.EventInfo)
  }

  // @@protoc_insertion_point(class_scope:profkom.events.EventInfo)
  private static final com.example.events_service.grpc.EventInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.events_service.grpc.EventInfo();
  }

  public static com.example.events_service.grpc.EventInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EventInfo>
      PARSER = new com.google.protobuf.AbstractParser<EventInfo>() {
    @java.lang.Override
    public EventInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<EventInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EventInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.events_service.grpc.EventInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

