// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: event.proto
// Protobuf Java Version: 4.28.2

package com.example.events_service.grpc;

public final class Event {
  private Event() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      Event.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_profkom_events_GetEventRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_profkom_events_GetEventRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_profkom_events_EventInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_profkom_events_EventInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013event.proto\022\016profkom.events\"#\n\017GetEven" +
      "tRequest\022\020\n\010event_id\030\001 \001(\t\"\361\001\n\tEventInfo" +
      "\022\020\n\010event_id\030\001 \001(\t\022\035\n\025registration_requi" +
      "red\030\002 \001(\010\022 \n\023points_per_attendee\030\003 \001(\003H\000" +
      "\210\001\001\022\030\n\013reviewed_by\030\004 \001(\003H\001\210\001\001\022\026\n\tschool_" +
      "id\030\005 \001(\003H\002\210\001\001\022\016\n\006status\030\006 \001(\t\022\031\n\021moderat" +
      "ion_status\030\007 \001(\tB\026\n\024_points_per_attendee" +
      "B\016\n\014_reviewed_byB\014\n\n_school_id2Z\n\020EventG" +
      "rpcService\022F\n\010GetEvent\022\037.profkom.events." +
      "GetEventRequest\032\031.profkom.events.EventIn" +
      "foB#\n\037com.example.events_service.grpcP\001b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_profkom_events_GetEventRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_profkom_events_GetEventRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_profkom_events_GetEventRequest_descriptor,
        new java.lang.String[] { "EventId", });
    internal_static_profkom_events_EventInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_profkom_events_EventInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_profkom_events_EventInfo_descriptor,
        new java.lang.String[] { "EventId", "RegistrationRequired", "PointsPerAttendee", "ReviewedBy", "SchoolId", "Status", "ModerationStatus", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
