// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: person.proto
// Protobuf Java Version: 4.28.2

package com.example.profile_service.grpc;

public interface PersonSummaryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:profkom.profile.PersonSummary)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 person_id = 1;</code>
   * @return The personId.
   */
  long getPersonId();

  /**
   * <code>string full_name = 2;</code>
   * @return The fullName.
   */
  java.lang.String getFullName();
  /**
   * <code>string full_name = 2;</code>
   * @return The bytes for fullName.
   */
  com.google.protobuf.ByteString
      getFullNameBytes();

  /**
   * <code>optional string group_title = 3;</code>
   * @return Whether the groupTitle field is set.
   */
  boolean hasGroupTitle();
  /**
   * <code>optional string group_title = 3;</code>
   * @return The groupTitle.
   */
  java.lang.String getGroupTitle();
  /**
   * <code>optional string group_title = 3;</code>
   * @return The bytes for groupTitle.
   */
  com.google.protobuf.ByteString
      getGroupTitleBytes();
}
