// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: event.proto
// Protobuf Java Version: 4.28.2

package com.example.events_service.grpc;

public interface EventInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:profkom.events.EventInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string event_id = 1;</code>
   * @return The eventId.
   */
  java.lang.String getEventId();
  /**
   * <code>string event_id = 1;</code>
   * @return The bytes for eventId.
   */
  com.google.protobuf.ByteString
      getEventIdBytes();

  /**
   * <code>bool registration_required = 2;</code>
   * @return The registrationRequired.
   */
  boolean getRegistrationRequired();

  /**
   * <code>optional int64 points_per_attendee = 3;</code>
   * @return Whether the pointsPerAttendee field is set.
   */
  boolean hasPointsPerAttendee();
  /**
   * <code>optional int64 points_per_attendee = 3;</code>
   * @return The pointsPerAttendee.
   */
  long getPointsPerAttendee();

  /**
   * <code>optional int64 reviewed_by = 4;</code>
   * @return Whether the reviewedBy field is set.
   */
  boolean hasReviewedBy();
  /**
   * <code>optional int64 reviewed_by = 4;</code>
   * @return The reviewedBy.
   */
  long getReviewedBy();

  /**
   * <code>optional int64 school_id = 5;</code>
   * @return Whether the schoolId field is set.
   */
  boolean hasSchoolId();
  /**
   * <code>optional int64 school_id = 5;</code>
   * @return The schoolId.
   */
  long getSchoolId();

  /**
   * <code>string status = 6;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 6;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>string moderation_status = 7;</code>
   * @return The moderationStatus.
   */
  java.lang.String getModerationStatus();
  /**
   * <code>string moderation_status = 7;</code>
   * @return The bytes for moderationStatus.
   */
  com.google.protobuf.ByteString
      getModerationStatusBytes();
}
