// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: event.proto
// Protobuf Java Version: 4.28.2

package com.example.events_service.grpc;

public interface GetEventRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:profkom.events.GetEventRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string event_id = 1;</code>
   * @return The eventId.
   */
  java.lang.String getEventId();
  /**
   * <code>string event_id = 1;</code>
   * @return The bytes for eventId.
   */
  com.google.protobuf.ByteString
      getEventIdBytes();
}
