// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: person.proto
// Protobuf Java Version: 4.28.2

package com.example.profile_service.grpc;

public final class Person {
  private Person() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      Person.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_profkom_profile_SearchPersonsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_profkom_profile_SearchPersonsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_profkom_profile_PersonSummary_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_profkom_profile_PersonSummary_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_profkom_profile_SearchPersonsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_profkom_profile_SearchPersonsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014person.proto\022\017profkom.profile\",\n\024Searc" +
      "hPersonsRequest\022\024\n\014lichnost_ids\030\001 \003(\003\"a\n" +
      "\rPersonSummary\022\023\n\013lichnost_id\030\001 \001(\003\022\021\n\tf" +
      "ull_name\030\002 \001(\t\022\030\n\013group_title\030\003 \001(\tH\000\210\001\001" +
      "B\016\n\014_group_title\"H\n\025SearchPersonsRespons" +
      "e\022/\n\007persons\030\001 \003(\0132\036.profkom.profile.Per" +
      "sonSummary2s\n\021PersonGrpcService\022^\n\rSearc" +
      "hPersons\022%.profkom.profile.SearchPersons" +
      "Request\032&.profkom.profile.SearchPersonsR" +
      "esponseB$\n com.example.profile_service.g" +
      "rpcP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_profkom_profile_SearchPersonsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_profkom_profile_SearchPersonsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_profkom_profile_SearchPersonsRequest_descriptor,
        new java.lang.String[] { "LichnostIds", });
    internal_static_profkom_profile_PersonSummary_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_profkom_profile_PersonSummary_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_profkom_profile_PersonSummary_descriptor,
        new java.lang.String[] { "LichnostId", "FullName", "GroupTitle", });
    internal_static_profkom_profile_SearchPersonsResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_profkom_profile_SearchPersonsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_profkom_profile_SearchPersonsResponse_descriptor,
        new java.lang.String[] { "Persons", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
