// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: person.proto
// Protobuf Java Version: 4.28.2

package com.example.profile_service.grpc;

/**
 * Protobuf type {@code profkom.profile.PersonSummary}
 */
public final class PersonSummary extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:profkom.profile.PersonSummary)
    PersonSummaryOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      PersonSummary.class.getName());
  }
  // Use PersonSummary.newBuilder() to construct.
  private PersonSummary(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PersonSummary() {
    fullName_ = "";
    groupTitle_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.profile_service.grpc.Person.internal_static_profkom_profile_PersonSummary_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.profile_service.grpc.Person.internal_static_profkom_profile_PersonSummary_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.profile_service.grpc.PersonSummary.class, com.example.profile_service.grpc.PersonSummary.Builder.class);
  }

  private int bitField0_;
  public static final int LICHNOST_ID_FIELD_NUMBER = 1;
  private long lichnostId_ = 0L;
  /**
   * <code>int64 lichnost_id = 1;</code>
   * @return The lichnostId.
   */
  @java.lang.Override
  public long getLichnostId() {
    return lichnostId_;
  }

  public static final int FULL_NAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object fullName_ = "";
  /**
   * <code>string full_name = 2;</code>
   * @return The fullName.
   */
  @java.lang.Override
  public java.lang.String getFullName() {
    java.lang.Object ref = fullName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fullName_ = s;
      return s;
    }
  }
  /**
   * <code>string full_name = 2;</code>
   * @return The bytes for fullName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFullNameBytes() {
    java.lang.Object ref = fullName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fullName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GROUP_TITLE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object groupTitle_ = "";
  /**
   * <code>optional string group_title = 3;</code>
   * @return Whether the groupTitle field is set.
   */
  @java.lang.Override
  public boolean hasGroupTitle() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string group_title = 3;</code>
   * @return The groupTitle.
   */
  @java.lang.Override
  public java.lang.String getGroupTitle() {
    java.lang.Object ref = groupTitle_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      groupTitle_ = s;
      return s;
    }
  }
  /**
   * <code>optional string group_title = 3;</code>
   * @return The bytes for groupTitle.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGroupTitleBytes() {
    java.lang.Object ref = groupTitle_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      groupTitle_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (lichnostId_ != 0L) {
      output.writeInt64(1, lichnostId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(fullName_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, fullName_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, groupTitle_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (lichnostId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, lichnostId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(fullName_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, fullName_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, groupTitle_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.profile_service.grpc.PersonSummary)) {
      return super.equals(obj);
    }
    com.example.profile_service.grpc.PersonSummary other = (com.example.profile_service.grpc.PersonSummary) obj;

    if (getLichnostId()
        != other.getLichnostId()) return false;
    if (!getFullName()
        .equals(other.getFullName())) return false;
    if (hasGroupTitle() != other.hasGroupTitle()) return false;
    if (hasGroupTitle()) {
      if (!getGroupTitle()
          .equals(other.getGroupTitle())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LICHNOST_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLichnostId());
    hash = (37 * hash) + FULL_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getFullName().hashCode();
    if (hasGroupTitle()) {
      hash = (37 * hash) + GROUP_TITLE_FIELD_NUMBER;
      hash = (53 * hash) + getGroupTitle().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.profile_service.grpc.PersonSummary parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.profile_service.grpc.PersonSummary parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.profile_service.grpc.PersonSummary parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.profile_service.grpc.PersonSummary parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.profile_service.grpc.PersonSummary parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.profile_service.grpc.PersonSummary parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.profile_service.grpc.PersonSummary parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.example.profile_service.grpc.PersonSummary parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.example.profile_service.grpc.PersonSummary parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.example.profile_service.grpc.PersonSummary parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.profile_service.grpc.PersonSummary parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.example.profile_service.grpc.PersonSummary parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.profile_service.grpc.PersonSummary prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code profkom.profile.PersonSummary}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:profkom.profile.PersonSummary)
      com.example.profile_service.grpc.PersonSummaryOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.profile_service.grpc.Person.internal_static_profkom_profile_PersonSummary_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.profile_service.grpc.Person.internal_static_profkom_profile_PersonSummary_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.profile_service.grpc.PersonSummary.class, com.example.profile_service.grpc.PersonSummary.Builder.class);
    }

    // Construct using com.example.profile_service.grpc.PersonSummary.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      lichnostId_ = 0L;
      fullName_ = "";
      groupTitle_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.profile_service.grpc.Person.internal_static_profkom_profile_PersonSummary_descriptor;
    }

    @java.lang.Override
    public com.example.profile_service.grpc.PersonSummary getDefaultInstanceForType() {
      return com.example.profile_service.grpc.PersonSummary.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.profile_service.grpc.PersonSummary build() {
      com.example.profile_service.grpc.PersonSummary result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.profile_service.grpc.PersonSummary buildPartial() {
      com.example.profile_service.grpc.PersonSummary result = new com.example.profile_service.grpc.PersonSummary(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.example.profile_service.grpc.PersonSummary result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.lichnostId_ = lichnostId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.fullName_ = fullName_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.groupTitle_ = groupTitle_;
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.profile_service.grpc.PersonSummary) {
        return mergeFrom((com.example.profile_service.grpc.PersonSummary)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.profile_service.grpc.PersonSummary other) {
      if (other == com.example.profile_service.grpc.PersonSummary.getDefaultInstance()) return this;
      if (other.getLichnostId() != 0L) {
        setLichnostId(other.getLichnostId());
      }
      if (!other.getFullName().isEmpty()) {
        fullName_ = other.fullName_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.hasGroupTitle()) {
        groupTitle_ = other.groupTitle_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              lichnostId_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              fullName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              groupTitle_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long lichnostId_ ;
    /**
     * <code>int64 lichnost_id = 1;</code>
     * @return The lichnostId.
     */
    @java.lang.Override
    public long getLichnostId() {
      return lichnostId_;
    }
    /**
     * <code>int64 lichnost_id = 1;</code>
     * @param value The lichnostId to set.
     * @return This builder for chaining.
     */
    public Builder setLichnostId(long value) {

      lichnostId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 lichnost_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearLichnostId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      lichnostId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object fullName_ = "";
    /**
     * <code>string full_name = 2;</code>
     * @return The fullName.
     */
    public java.lang.String getFullName() {
      java.lang.Object ref = fullName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fullName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string full_name = 2;</code>
     * @return The bytes for fullName.
     */
    public com.google.protobuf.ByteString
        getFullNameBytes() {
      java.lang.Object ref = fullName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fullName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string full_name = 2;</code>
     * @param value The fullName to set.
     * @return This builder for chaining.
     */
    public Builder setFullName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      fullName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string full_name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearFullName() {
      fullName_ = getDefaultInstance().getFullName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string full_name = 2;</code>
     * @param value The bytes for fullName to set.
     * @return This builder for chaining.
     */
    public Builder setFullNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      fullName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object groupTitle_ = "";
    /**
     * <code>optional string group_title = 3;</code>
     * @return Whether the groupTitle field is set.
     */
    public boolean hasGroupTitle() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string group_title = 3;</code>
     * @return The groupTitle.
     */
    public java.lang.String getGroupTitle() {
      java.lang.Object ref = groupTitle_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        groupTitle_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string group_title = 3;</code>
     * @return The bytes for groupTitle.
     */
    public com.google.protobuf.ByteString
        getGroupTitleBytes() {
      java.lang.Object ref = groupTitle_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        groupTitle_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string group_title = 3;</code>
     * @param value The groupTitle to set.
     * @return This builder for chaining.
     */
    public Builder setGroupTitle(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      groupTitle_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional string group_title = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearGroupTitle() {
      groupTitle_ = getDefaultInstance().getGroupTitle();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>optional string group_title = 3;</code>
     * @param value The bytes for groupTitle to set.
     * @return This builder for chaining.
     */
    public Builder setGroupTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      groupTitle_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:profkom.profile.PersonSummary)
  }

  // @@protoc_insertion_point(class_scope:profkom.profile.PersonSummary)
  private static final com.example.profile_service.grpc.PersonSummary DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.profile_service.grpc.PersonSummary();
  }

  public static com.example.profile_service.grpc.PersonSummary getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PersonSummary>
      PARSER = new com.google.protobuf.AbstractParser<PersonSummary>() {
    @java.lang.Override
    public PersonSummary parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PersonSummary> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PersonSummary> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.profile_service.grpc.PersonSummary getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

