// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: person.proto
// Protobuf Java Version: 4.28.2

package com.example.profile_service.grpc;

public interface SearchPersonsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:profkom.profile.SearchPersonsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int64 lichnost_ids = 1;</code>
   * @return A list containing the lichnostIds.
   */
  java.util.List<java.lang.Long> getLichnostIdsList();
  /**
   * <code>repeated int64 lichnost_ids = 1;</code>
   * @return The count of lichnostIds.
   */
  int getLichnostIdsCount();
  /**
   * <code>repeated int64 lichnost_ids = 1;</code>
   * @param index The index of the element to return.
   * @return The lichnostIds at the given index.
   */
  long getLichnostIds(int index);
}
