// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: person.proto
// Protobuf Java Version: 4.28.2

package com.example.profile_service.grpc;

/**
 * Protobuf type {@code profkom.profile.SearchPersonsRequest}
 */
public final class SearchPersonsRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:profkom.profile.SearchPersonsRequest)
    SearchPersonsRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      SearchPersonsRequest.class.getName());
  }
  // Use SearchPersonsRequest.newBuilder() to construct.
  private SearchPersonsRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private SearchPersonsRequest() {
    lichnostIds_ = emptyLongList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.profile_service.grpc.Person.internal_static_profkom_profile_SearchPersonsRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.profile_service.grpc.Person.internal_static_profkom_profile_SearchPersonsRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.profile_service.grpc.SearchPersonsRequest.class, com.example.profile_service.grpc.SearchPersonsRequest.Builder.class);
  }

  public static final int LICHNOST_IDS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.LongList lichnostIds_ =
      emptyLongList();
  /**
   * <code>repeated int64 lichnost_ids = 1;</code>
   * @return A list containing the lichnostIds.
   */
  @java.lang.Override
  public java.util.List<java.lang.Long>
      getLichnostIdsList() {
    return lichnostIds_;
  }
  /**
   * <code>repeated int64 lichnost_ids = 1;</code>
   * @return The count of lichnostIds.
   */
  public int getLichnostIdsCount() {
    return lichnostIds_.size();
  }
  /**
   * <code>repeated int64 lichnost_ids = 1;</code>
   * @param index The index of the element to return.
   * @return The lichnostIds at the given index.
   */
  public long getLichnostIds(int index) {
    return lichnostIds_.getLong(index);
  }
  private int lichnostIdsMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (getLichnostIdsList().size() > 0) {
      output.writeUInt32NoTag(10);
      output.writeUInt32NoTag(lichnostIdsMemoizedSerializedSize);
    }
    for (int i = 0; i < lichnostIds_.size(); i++) {
      output.writeInt64NoTag(lichnostIds_.getLong(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < lichnostIds_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt64SizeNoTag(lichnostIds_.getLong(i));
      }
      size += dataSize;
      if (!getLichnostIdsList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      lichnostIdsMemoizedSerializedSize = dataSize;
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.profile_service.grpc.SearchPersonsRequest)) {
      return super.equals(obj);
    }
    com.example.profile_service.grpc.SearchPersonsRequest other = (com.example.profile_service.grpc.SearchPersonsRequest) obj;

    if (!getLichnostIdsList()
        .equals(other.getLichnostIdsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getLichnostIdsCount() > 0) {
      hash = (37 * hash) + LICHNOST_IDS_FIELD_NUMBER;
      hash = (53 * hash) + getLichnostIdsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.profile_service.grpc.SearchPersonsRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.profile_service.grpc.SearchPersonsRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.profile_service.grpc.SearchPersonsRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.profile_service.grpc.SearchPersonsRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.profile_service.grpc.SearchPersonsRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.profile_service.grpc.SearchPersonsRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.profile_service.grpc.SearchPersonsRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.example.profile_service.grpc.SearchPersonsRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.example.profile_service.grpc.SearchPersonsRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.example.profile_service.grpc.SearchPersonsRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.profile_service.grpc.SearchPersonsRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.example.profile_service.grpc.SearchPersonsRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.profile_service.grpc.SearchPersonsRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code profkom.profile.SearchPersonsRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:profkom.profile.SearchPersonsRequest)
      com.example.profile_service.grpc.SearchPersonsRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.profile_service.grpc.Person.internal_static_profkom_profile_SearchPersonsRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.profile_service.grpc.Person.internal_static_profkom_profile_SearchPersonsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.profile_service.grpc.SearchPersonsRequest.class, com.example.profile_service.grpc.SearchPersonsRequest.Builder.class);
    }

    // Construct using com.example.profile_service.grpc.SearchPersonsRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      lichnostIds_ = emptyLongList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.profile_service.grpc.Person.internal_static_profkom_profile_SearchPersonsRequest_descriptor;
    }

    @java.lang.Override
    public com.example.profile_service.grpc.SearchPersonsRequest getDefaultInstanceForType() {
      return com.example.profile_service.grpc.SearchPersonsRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.profile_service.grpc.SearchPersonsRequest build() {
      com.example.profile_service.grpc.SearchPersonsRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.profile_service.grpc.SearchPersonsRequest buildPartial() {
      com.example.profile_service.grpc.SearchPersonsRequest result = new com.example.profile_service.grpc.SearchPersonsRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.example.profile_service.grpc.SearchPersonsRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        lichnostIds_.makeImmutable();
        result.lichnostIds_ = lichnostIds_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.profile_service.grpc.SearchPersonsRequest) {
        return mergeFrom((com.example.profile_service.grpc.SearchPersonsRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.profile_service.grpc.SearchPersonsRequest other) {
      if (other == com.example.profile_service.grpc.SearchPersonsRequest.getDefaultInstance()) return this;
      if (!other.lichnostIds_.isEmpty()) {
        if (lichnostIds_.isEmpty()) {
          lichnostIds_ = other.lichnostIds_;
          lichnostIds_.makeImmutable();
          bitField0_ |= 0x00000001;
        } else {
          ensureLichnostIdsIsMutable();
          lichnostIds_.addAll(other.lichnostIds_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              long v = input.readInt64();
              ensureLichnostIdsIsMutable();
              lichnostIds_.addLong(v);
              break;
            } // case 8
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureLichnostIdsIsMutable();
              while (input.getBytesUntilLimit() > 0) {
                lichnostIds_.addLong(input.readInt64());
              }
              input.popLimit(limit);
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.Internal.LongList lichnostIds_ = emptyLongList();
    private void ensureLichnostIdsIsMutable() {
      if (!lichnostIds_.isModifiable()) {
        lichnostIds_ = makeMutableCopy(lichnostIds_);
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>repeated int64 lichnost_ids = 1;</code>
     * @return A list containing the lichnostIds.
     */
    public java.util.List<java.lang.Long>
        getLichnostIdsList() {
      lichnostIds_.makeImmutable();
      return lichnostIds_;
    }
    /**
     * <code>repeated int64 lichnost_ids = 1;</code>
     * @return The count of lichnostIds.
     */
    public int getLichnostIdsCount() {
      return lichnostIds_.size();
    }
    /**
     * <code>repeated int64 lichnost_ids = 1;</code>
     * @param index The index of the element to return.
     * @return The lichnostIds at the given index.
     */
    public long getLichnostIds(int index) {
      return lichnostIds_.getLong(index);
    }
    /**
     * <code>repeated int64 lichnost_ids = 1;</code>
     * @param index The index to set the value at.
     * @param value The lichnostIds to set.
     * @return This builder for chaining.
     */
    public Builder setLichnostIds(
        int index, long value) {

      ensureLichnostIdsIsMutable();
      lichnostIds_.setLong(index, value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 lichnost_ids = 1;</code>
     * @param value The lichnostIds to add.
     * @return This builder for chaining.
     */
    public Builder addLichnostIds(long value) {

      ensureLichnostIdsIsMutable();
      lichnostIds_.addLong(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 lichnost_ids = 1;</code>
     * @param values The lichnostIds to add.
     * @return This builder for chaining.
     */
    public Builder addAllLichnostIds(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureLichnostIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, lichnostIds_);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 lichnost_ids = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearLichnostIds() {
      lichnostIds_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:profkom.profile.SearchPersonsRequest)
  }

  // @@protoc_insertion_point(class_scope:profkom.profile.SearchPersonsRequest)
  private static final com.example.profile_service.grpc.SearchPersonsRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.profile_service.grpc.SearchPersonsRequest();
  }

  public static com.example.profile_service.grpc.SearchPersonsRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SearchPersonsRequest>
      PARSER = new com.google.protobuf.AbstractParser<SearchPersonsRequest>() {
    @java.lang.Override
    public SearchPersonsRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SearchPersonsRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SearchPersonsRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.profile_service.grpc.SearchPersonsRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

