// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: person.proto
// Protobuf Java Version: 4.28.2

package com.example.profile_service.grpc;

public interface SearchPersonsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:profkom.profile.SearchPersonsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .profkom.profile.PersonSummary persons = 1;</code>
   */
  java.util.List<com.example.profile_service.grpc.PersonSummary> 
      getPersonsList();
  /**
   * <code>repeated .profkom.profile.PersonSummary persons = 1;</code>
   */
  com.example.profile_service.grpc.PersonSummary getPersons(int index);
  /**
   * <code>repeated .profkom.profile.PersonSummary persons = 1;</code>
   */
  int getPersonsCount();
  /**
   * <code>repeated .profkom.profile.PersonSummary persons = 1;</code>
   */
  java.util.List<? extends com.example.profile_service.grpc.PersonSummaryOrBuilder> 
      getPersonsOrBuilderList();
  /**
   * <code>repeated .profkom.profile.PersonSummary persons = 1;</code>
   */
  com.example.profile_service.grpc.PersonSummaryOrBuilder getPersonsOrBuilder(
      int index);
}
