// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: person.proto
// Protobuf Java Version: 4.28.2

package com.example.profile_service.grpc;

/**
 * Protobuf type {@code profkom.profile.SearchPersonsResponse}
 */
public final class SearchPersonsResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:profkom.profile.SearchPersonsResponse)
    SearchPersonsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      SearchPersonsResponse.class.getName());
  }
  // Use SearchPersonsResponse.newBuilder() to construct.
  private SearchPersonsResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private SearchPersonsResponse() {
    persons_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.profile_service.grpc.Person.internal_static_profkom_profile_SearchPersonsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.profile_service.grpc.Person.internal_static_profkom_profile_SearchPersonsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.profile_service.grpc.SearchPersonsResponse.class, com.example.profile_service.grpc.SearchPersonsResponse.Builder.class);
  }

  public static final int PERSONS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.example.profile_service.grpc.PersonSummary> persons_;
  /**
   * <code>repeated .profkom.profile.PersonSummary persons = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.example.profile_service.grpc.PersonSummary> getPersonsList() {
    return persons_;
  }
  /**
   * <code>repeated .profkom.profile.PersonSummary persons = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.example.profile_service.grpc.PersonSummaryOrBuilder> 
      getPersonsOrBuilderList() {
    return persons_;
  }
  /**
   * <code>repeated .profkom.profile.PersonSummary persons = 1;</code>
   */
  @java.lang.Override
  public int getPersonsCount() {
    return persons_.size();
  }
  /**
   * <code>repeated .profkom.profile.PersonSummary persons = 1;</code>
   */
  @java.lang.Override
  public com.example.profile_service.grpc.PersonSummary getPersons(int index) {
    return persons_.get(index);
  }
  /**
   * <code>repeated .profkom.profile.PersonSummary persons = 1;</code>
   */
  @java.lang.Override
  public com.example.profile_service.grpc.PersonSummaryOrBuilder getPersonsOrBuilder(
      int index) {
    return persons_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < persons_.size(); i++) {
      output.writeMessage(1, persons_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < persons_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, persons_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.profile_service.grpc.SearchPersonsResponse)) {
      return super.equals(obj);
    }
    com.example.profile_service.grpc.SearchPersonsResponse other = (com.example.profile_service.grpc.SearchPersonsResponse) obj;

    if (!getPersonsList()
        .equals(other.getPersonsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getPersonsCount() > 0) {
      hash = (37 * hash) + PERSONS_FIELD_NUMBER;
      hash = (53 * hash) + getPersonsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.profile_service.grpc.SearchPersonsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.profile_service.grpc.SearchPersonsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.profile_service.grpc.SearchPersonsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.profile_service.grpc.SearchPersonsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.profile_service.grpc.SearchPersonsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.profile_service.grpc.SearchPersonsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.profile_service.grpc.SearchPersonsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.example.profile_service.grpc.SearchPersonsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.example.profile_service.grpc.SearchPersonsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.example.profile_service.grpc.SearchPersonsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.profile_service.grpc.SearchPersonsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.example.profile_service.grpc.SearchPersonsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.profile_service.grpc.SearchPersonsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code profkom.profile.SearchPersonsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:profkom.profile.SearchPersonsResponse)
      com.example.profile_service.grpc.SearchPersonsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.profile_service.grpc.Person.internal_static_profkom_profile_SearchPersonsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.profile_service.grpc.Person.internal_static_profkom_profile_SearchPersonsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.profile_service.grpc.SearchPersonsResponse.class, com.example.profile_service.grpc.SearchPersonsResponse.Builder.class);
    }

    // Construct using com.example.profile_service.grpc.SearchPersonsResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (personsBuilder_ == null) {
        persons_ = java.util.Collections.emptyList();
      } else {
        persons_ = null;
        personsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.profile_service.grpc.Person.internal_static_profkom_profile_SearchPersonsResponse_descriptor;
    }

    @java.lang.Override
    public com.example.profile_service.grpc.SearchPersonsResponse getDefaultInstanceForType() {
      return com.example.profile_service.grpc.SearchPersonsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.profile_service.grpc.SearchPersonsResponse build() {
      com.example.profile_service.grpc.SearchPersonsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.profile_service.grpc.SearchPersonsResponse buildPartial() {
      com.example.profile_service.grpc.SearchPersonsResponse result = new com.example.profile_service.grpc.SearchPersonsResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.example.profile_service.grpc.SearchPersonsResponse result) {
      if (personsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          persons_ = java.util.Collections.unmodifiableList(persons_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.persons_ = persons_;
      } else {
        result.persons_ = personsBuilder_.build();
      }
    }

    private void buildPartial0(com.example.profile_service.grpc.SearchPersonsResponse result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.profile_service.grpc.SearchPersonsResponse) {
        return mergeFrom((com.example.profile_service.grpc.SearchPersonsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.profile_service.grpc.SearchPersonsResponse other) {
      if (other == com.example.profile_service.grpc.SearchPersonsResponse.getDefaultInstance()) return this;
      if (personsBuilder_ == null) {
        if (!other.persons_.isEmpty()) {
          if (persons_.isEmpty()) {
            persons_ = other.persons_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePersonsIsMutable();
            persons_.addAll(other.persons_);
          }
          onChanged();
        }
      } else {
        if (!other.persons_.isEmpty()) {
          if (personsBuilder_.isEmpty()) {
            personsBuilder_.dispose();
            personsBuilder_ = null;
            persons_ = other.persons_;
            bitField0_ = (bitField0_ & ~0x00000001);
            personsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getPersonsFieldBuilder() : null;
          } else {
            personsBuilder_.addAllMessages(other.persons_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.example.profile_service.grpc.PersonSummary m =
                  input.readMessage(
                      com.example.profile_service.grpc.PersonSummary.parser(),
                      extensionRegistry);
              if (personsBuilder_ == null) {
                ensurePersonsIsMutable();
                persons_.add(m);
              } else {
                personsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.example.profile_service.grpc.PersonSummary> persons_ =
      java.util.Collections.emptyList();
    private void ensurePersonsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        persons_ = new java.util.ArrayList<com.example.profile_service.grpc.PersonSummary>(persons_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.example.profile_service.grpc.PersonSummary, com.example.profile_service.grpc.PersonSummary.Builder, com.example.profile_service.grpc.PersonSummaryOrBuilder> personsBuilder_;

    /**
     * <code>repeated .profkom.profile.PersonSummary persons = 1;</code>
     */
    public java.util.List<com.example.profile_service.grpc.PersonSummary> getPersonsList() {
      if (personsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(persons_);
      } else {
        return personsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .profkom.profile.PersonSummary persons = 1;</code>
     */
    public int getPersonsCount() {
      if (personsBuilder_ == null) {
        return persons_.size();
      } else {
        return personsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .profkom.profile.PersonSummary persons = 1;</code>
     */
    public com.example.profile_service.grpc.PersonSummary getPersons(int index) {
      if (personsBuilder_ == null) {
        return persons_.get(index);
      } else {
        return personsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .profkom.profile.PersonSummary persons = 1;</code>
     */
    public Builder setPersons(
        int index, com.example.profile_service.grpc.PersonSummary value) {
      if (personsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePersonsIsMutable();
        persons_.set(index, value);
        onChanged();
      } else {
        personsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .profkom.profile.PersonSummary persons = 1;</code>
     */
    public Builder setPersons(
        int index, com.example.profile_service.grpc.PersonSummary.Builder builderForValue) {
      if (personsBuilder_ == null) {
        ensurePersonsIsMutable();
        persons_.set(index, builderForValue.build());
        onChanged();
      } else {
        personsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .profkom.profile.PersonSummary persons = 1;</code>
     */
    public Builder addPersons(com.example.profile_service.grpc.PersonSummary value) {
      if (personsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePersonsIsMutable();
        persons_.add(value);
        onChanged();
      } else {
        personsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .profkom.profile.PersonSummary persons = 1;</code>
     */
    public Builder addPersons(
        int index, com.example.profile_service.grpc.PersonSummary value) {
      if (personsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePersonsIsMutable();
        persons_.add(index, value);
        onChanged();
      } else {
        personsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .profkom.profile.PersonSummary persons = 1;</code>
     */
    public Builder addPersons(
        com.example.profile_service.grpc.PersonSummary.Builder builderForValue) {
      if (personsBuilder_ == null) {
        ensurePersonsIsMutable();
        persons_.add(builderForValue.build());
        onChanged();
      } else {
        personsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .profkom.profile.PersonSummary persons = 1;</code>
     */
    public Builder addPersons(
        int index, com.example.profile_service.grpc.PersonSummary.Builder builderForValue) {
      if (personsBuilder_ == null) {
        ensurePersonsIsMutable();
        persons_.add(index, builderForValue.build());
        onChanged();
      } else {
        personsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .profkom.profile.PersonSummary persons = 1;</code>
     */
    public Builder addAllPersons(
        java.lang.Iterable<? extends com.example.profile_service.grpc.PersonSummary> values) {
      if (personsBuilder_ == null) {
        ensurePersonsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, persons_);
        onChanged();
      } else {
        personsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .profkom.profile.PersonSummary persons = 1;</code>
     */
    public Builder clearPersons() {
      if (personsBuilder_ == null) {
        persons_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        personsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .profkom.profile.PersonSummary persons = 1;</code>
     */
    public Builder removePersons(int index) {
      if (personsBuilder_ == null) {
        ensurePersonsIsMutable();
        persons_.remove(index);
        onChanged();
      } else {
        personsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .profkom.profile.PersonSummary persons = 1;</code>
     */
    public com.example.profile_service.grpc.PersonSummary.Builder getPersonsBuilder(
        int index) {
      return getPersonsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .profkom.profile.PersonSummary persons = 1;</code>
     */
    public com.example.profile_service.grpc.PersonSummaryOrBuilder getPersonsOrBuilder(
        int index) {
      if (personsBuilder_ == null) {
        return persons_.get(index);  } else {
        return personsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .profkom.profile.PersonSummary persons = 1;</code>
     */
    public java.util.List<? extends com.example.profile_service.grpc.PersonSummaryOrBuilder> 
         getPersonsOrBuilderList() {
      if (personsBuilder_ != null) {
        return personsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(persons_);
      }
    }
    /**
     * <code>repeated .profkom.profile.PersonSummary persons = 1;</code>
     */
    public com.example.profile_service.grpc.PersonSummary.Builder addPersonsBuilder() {
      return getPersonsFieldBuilder().addBuilder(
          com.example.profile_service.grpc.PersonSummary.getDefaultInstance());
    }
    /**
     * <code>repeated .profkom.profile.PersonSummary persons = 1;</code>
     */
    public com.example.profile_service.grpc.PersonSummary.Builder addPersonsBuilder(
        int index) {
      return getPersonsFieldBuilder().addBuilder(
          index, com.example.profile_service.grpc.PersonSummary.getDefaultInstance());
    }
    /**
     * <code>repeated .profkom.profile.PersonSummary persons = 1;</code>
     */
    public java.util.List<com.example.profile_service.grpc.PersonSummary.Builder> 
         getPersonsBuilderList() {
      return getPersonsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.example.profile_service.grpc.PersonSummary, com.example.profile_service.grpc.PersonSummary.Builder, com.example.profile_service.grpc.PersonSummaryOrBuilder> 
        getPersonsFieldBuilder() {
      if (personsBuilder_ == null) {
        personsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.example.profile_service.grpc.PersonSummary, com.example.profile_service.grpc.PersonSummary.Builder, com.example.profile_service.grpc.PersonSummaryOrBuilder>(
                persons_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        persons_ = null;
      }
      return personsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:profkom.profile.SearchPersonsResponse)
  }

  // @@protoc_insertion_point(class_scope:profkom.profile.SearchPersonsResponse)
  private static final com.example.profile_service.grpc.SearchPersonsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.profile_service.grpc.SearchPersonsResponse();
  }

  public static com.example.profile_service.grpc.SearchPersonsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SearchPersonsResponse>
      PARSER = new com.google.protobuf.AbstractParser<SearchPersonsResponse>() {
    @java.lang.Override
    public SearchPersonsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SearchPersonsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SearchPersonsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.profile_service.grpc.SearchPersonsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

