// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: transactions.proto
// Protobuf Java Version: 4.28.2

package com.example.transactions_service.grpc;

/**
 * Protobuf type {@code profkom.transactions.ChargePurchaseRequest}
 */
public final class ChargePurchaseRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:profkom.transactions.ChargePurchaseRequest)
    ChargePurchaseRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      ChargePurchaseRequest.class.getName());
  }
  // Use ChargePurchaseRequest.newBuilder() to construct.
  private ChargePurchaseRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ChargePurchaseRequest() {
    purchaseId_ = "";
    description_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.transactions_service.grpc.Transactions.internal_static_profkom_transactions_ChargePurchaseRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.transactions_service.grpc.Transactions.internal_static_profkom_transactions_ChargePurchaseRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.transactions_service.grpc.ChargePurchaseRequest.class, com.example.transactions_service.grpc.ChargePurchaseRequest.Builder.class);
  }

  public static final int BUYER_USER_ID_FIELD_NUMBER = 1;
  private long buyerUserId_ = 0L;
  /**
   * <code>int64 buyer_user_id = 1;</code>
   * @return The buyerUserId.
   */
  @java.lang.Override
  public long getBuyerUserId() {
    return buyerUserId_;
  }

  public static final int AMOUNT_FIELD_NUMBER = 2;
  private long amount_ = 0L;
  /**
   * <code>int64 amount = 2;</code>
   * @return The amount.
   */
  @java.lang.Override
  public long getAmount() {
    return amount_;
  }

  public static final int PURCHASE_ID_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object purchaseId_ = "";
  /**
   * <code>string purchase_id = 3;</code>
   * @return The purchaseId.
   */
  @java.lang.Override
  public java.lang.String getPurchaseId() {
    java.lang.Object ref = purchaseId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      purchaseId_ = s;
      return s;
    }
  }
  /**
   * <code>string purchase_id = 3;</code>
   * @return The bytes for purchaseId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPurchaseIdBytes() {
    java.lang.Object ref = purchaseId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      purchaseId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object description_ = "";
  /**
   * <code>string description = 4;</code>
   * @return The description.
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <code>string description = 4;</code>
   * @return The bytes for description.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (buyerUserId_ != 0L) {
      output.writeInt64(1, buyerUserId_);
    }
    if (amount_ != 0L) {
      output.writeInt64(2, amount_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(purchaseId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, purchaseId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(description_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, description_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (buyerUserId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, buyerUserId_);
    }
    if (amount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, amount_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(purchaseId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, purchaseId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(description_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, description_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.transactions_service.grpc.ChargePurchaseRequest)) {
      return super.equals(obj);
    }
    com.example.transactions_service.grpc.ChargePurchaseRequest other = (com.example.transactions_service.grpc.ChargePurchaseRequest) obj;

    if (getBuyerUserId()
        != other.getBuyerUserId()) return false;
    if (getAmount()
        != other.getAmount()) return false;
    if (!getPurchaseId()
        .equals(other.getPurchaseId())) return false;
    if (!getDescription()
        .equals(other.getDescription())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BUYER_USER_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getBuyerUserId());
    hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getAmount());
    hash = (37 * hash) + PURCHASE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getPurchaseId().hashCode();
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.transactions_service.grpc.ChargePurchaseRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.transactions_service.grpc.ChargePurchaseRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.transactions_service.grpc.ChargePurchaseRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.transactions_service.grpc.ChargePurchaseRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.transactions_service.grpc.ChargePurchaseRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.transactions_service.grpc.ChargePurchaseRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.transactions_service.grpc.ChargePurchaseRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.example.transactions_service.grpc.ChargePurchaseRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.example.transactions_service.grpc.ChargePurchaseRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.example.transactions_service.grpc.ChargePurchaseRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.transactions_service.grpc.ChargePurchaseRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.example.transactions_service.grpc.ChargePurchaseRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.transactions_service.grpc.ChargePurchaseRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code profkom.transactions.ChargePurchaseRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:profkom.transactions.ChargePurchaseRequest)
      com.example.transactions_service.grpc.ChargePurchaseRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.transactions_service.grpc.Transactions.internal_static_profkom_transactions_ChargePurchaseRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.transactions_service.grpc.Transactions.internal_static_profkom_transactions_ChargePurchaseRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.transactions_service.grpc.ChargePurchaseRequest.class, com.example.transactions_service.grpc.ChargePurchaseRequest.Builder.class);
    }

    // Construct using com.example.transactions_service.grpc.ChargePurchaseRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      buyerUserId_ = 0L;
      amount_ = 0L;
      purchaseId_ = "";
      description_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.transactions_service.grpc.Transactions.internal_static_profkom_transactions_ChargePurchaseRequest_descriptor;
    }

    @java.lang.Override
    public com.example.transactions_service.grpc.ChargePurchaseRequest getDefaultInstanceForType() {
      return com.example.transactions_service.grpc.ChargePurchaseRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.transactions_service.grpc.ChargePurchaseRequest build() {
      com.example.transactions_service.grpc.ChargePurchaseRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.transactions_service.grpc.ChargePurchaseRequest buildPartial() {
      com.example.transactions_service.grpc.ChargePurchaseRequest result = new com.example.transactions_service.grpc.ChargePurchaseRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.example.transactions_service.grpc.ChargePurchaseRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.buyerUserId_ = buyerUserId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.amount_ = amount_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.purchaseId_ = purchaseId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.description_ = description_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.transactions_service.grpc.ChargePurchaseRequest) {
        return mergeFrom((com.example.transactions_service.grpc.ChargePurchaseRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.transactions_service.grpc.ChargePurchaseRequest other) {
      if (other == com.example.transactions_service.grpc.ChargePurchaseRequest.getDefaultInstance()) return this;
      if (other.getBuyerUserId() != 0L) {
        setBuyerUserId(other.getBuyerUserId());
      }
      if (other.getAmount() != 0L) {
        setAmount(other.getAmount());
      }
      if (!other.getPurchaseId().isEmpty()) {
        purchaseId_ = other.purchaseId_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              buyerUserId_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              amount_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              purchaseId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              description_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long buyerUserId_ ;
    /**
     * <code>int64 buyer_user_id = 1;</code>
     * @return The buyerUserId.
     */
    @java.lang.Override
    public long getBuyerUserId() {
      return buyerUserId_;
    }
    /**
     * <code>int64 buyer_user_id = 1;</code>
     * @param value The buyerUserId to set.
     * @return This builder for chaining.
     */
    public Builder setBuyerUserId(long value) {

      buyerUserId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 buyer_user_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearBuyerUserId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      buyerUserId_ = 0L;
      onChanged();
      return this;
    }

    private long amount_ ;
    /**
     * <code>int64 amount = 2;</code>
     * @return The amount.
     */
    @java.lang.Override
    public long getAmount() {
      return amount_;
    }
    /**
     * <code>int64 amount = 2;</code>
     * @param value The amount to set.
     * @return This builder for chaining.
     */
    public Builder setAmount(long value) {

      amount_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int64 amount = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAmount() {
      bitField0_ = (bitField0_ & ~0x00000002);
      amount_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object purchaseId_ = "";
    /**
     * <code>string purchase_id = 3;</code>
     * @return The purchaseId.
     */
    public java.lang.String getPurchaseId() {
      java.lang.Object ref = purchaseId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        purchaseId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string purchase_id = 3;</code>
     * @return The bytes for purchaseId.
     */
    public com.google.protobuf.ByteString
        getPurchaseIdBytes() {
      java.lang.Object ref = purchaseId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        purchaseId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string purchase_id = 3;</code>
     * @param value The purchaseId to set.
     * @return This builder for chaining.
     */
    public Builder setPurchaseId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      purchaseId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string purchase_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPurchaseId() {
      purchaseId_ = getDefaultInstance().getPurchaseId();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string purchase_id = 3;</code>
     * @param value The bytes for purchaseId to set.
     * @return This builder for chaining.
     */
    public Builder setPurchaseIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      purchaseId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     * <code>string description = 4;</code>
     * @return The description.
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string description = 4;</code>
     * @return The bytes for description.
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string description = 4;</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      description_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string description = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      description_ = getDefaultInstance().getDescription();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string description = 4;</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      description_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:profkom.transactions.ChargePurchaseRequest)
  }

  // @@protoc_insertion_point(class_scope:profkom.transactions.ChargePurchaseRequest)
  private static final com.example.transactions_service.grpc.ChargePurchaseRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.transactions_service.grpc.ChargePurchaseRequest();
  }

  public static com.example.transactions_service.grpc.ChargePurchaseRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ChargePurchaseRequest>
      PARSER = new com.google.protobuf.AbstractParser<ChargePurchaseRequest>() {
    @java.lang.Override
    public ChargePurchaseRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ChargePurchaseRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ChargePurchaseRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.transactions_service.grpc.ChargePurchaseRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

